#!/usr/bin/env python3
"""
Pull PRODUCTION source into tests/build/ so the C++ harness compiles the real
code rather than a paraphrase of it.

Nothing here rewrites logic. Every extracted region is copied verbatim and the
extraction fails loudly if an anchor moves, so a test can never silently drift
away from the code it claims to cover.
"""
import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "tests" / "build"
CONFIG = ROOT / "MQL5/Include/XAUM15/Config.mqh"
SETUPS = ROOT / "MQL5/Include/XAUM15/Setups.mqh"
DECLOG = ROOT / "MQL5/Include/XAUM15/DecisionLog.mqh"
EA = ROOT / "MQL5/Experts/XAUM15/XAU_M15_Institutional_Adaptive.mq5"


def read(p):
    return p.read_text(encoding="utf-8", errors="surrogateescape")


def grab(src, pattern, what, flags=re.S):
    m = re.search(pattern, src, flags)
    if not m:
        sys.exit(f"EXTRACT FAILED: anchor for {what} not found. "
                 f"The source moved; fix the anchor rather than the test.")
    return m.group(0)


def grab_block(src, start_pat, what):
    """Take a function DEFINITION from start_pat to its matching brace.

    A forward declaration matches the same pattern and is followed by ';',
    not '{'. Taking the first match would silently capture the body of
    whatever function is declared next, so declarations are skipped.
    """
    for m in re.finditer(start_pat, src):
        # walk to the end of the parameter list
        k = src.index("(", m.start())
        depth = 0
        while k < len(src):
            depth += (src[k] == "(") - (src[k] == ")")
            if depth == 0:
                break
            k += 1
        tail = src[k + 1:k + 200].lstrip()
        if tail.startswith(";"):
            continue                       # forward declaration, not the body
        if not tail.startswith("{"):
            continue
        i = src.index("{", k)
        depth = 0
        for j in range(i, len(src)):
            depth += (src[j] == "{") - (src[j] == "}")
            if depth == 0:
                return src[m.start():j + 1]
        sys.exit(f"EXTRACT FAILED: unbalanced braces in {what}")
    sys.exit(f"EXTRACT FAILED: no DEFINITION found for {what} "
             f"(only declarations?). Fix the anchor, not the test.")


def main():
    BUILD.mkdir(parents=True, exist_ok=True)
    cfg, setups, ea = read(CONFIG), read(SETUPS), read(EA)

    # ---- enums + TradeSignal, verbatim from Config.mqh -------------------
    enums = []
    for name in ["ENUM_REGIME", "ENUM_SETUP_ID", "ENUM_QUALITY", "ENUM_SWEEP_SIDE"]:
        enums.append(grab(cfg, r"enum\s+" + name + r"\s*\{.*?\};", name))
    ts = grab(cfg, r"struct\s+TradeSignal\s*\{.*?\n\s*\};", "TradeSignal")

    (BUILD / "Config.mqh").write_text(
        "// GENERATED by tests/extract_source.py - do not edit.\n"
        "// Enums and TradeSignal are copied VERBATIM from Config.mqh.\n"
        "#pragma once\n#include \"../mql5_shim.h\"\n\n"
        + "\n\n".join(enums) + "\n\n" + ts + "\n\n"
        "// Inputs the extracted code reads. Tests set these directly.\n"
        "extern bool   InpWriteDecisionLog;\n"
        "extern string InpDecisionLogFile;\n"
        "extern double InpTrendZoneMin;\n"
        "extern double InpTrendZoneMax;\n"
        "extern int    InpTrendSmaPeriod;\n",
        encoding="utf-8")

    # ---- DecisionLog.mqh copied byte for byte ----------------------------
    raw = DECLOG.read_bytes()
    (BUILD / "DecisionLog.mqh").write_bytes(raw)
    digest = hashlib.sha256(raw).hexdigest()[:16]

    # ---- ZeroSignal + StampSignalContext, verbatim -----------------------
    zero = grab_block(setups, r"void\s+ZeroSignal\s*\(", "ZeroSignal")
    stamp = grab_block(setups, r"void\s+StampSignalContext\s*\(", "StampSignalContext")
    (BUILD / "setups_extract.h").write_text(
        "// GENERATED - verbatim from Setups.mqh\n#pragma once\n"
        "#include \"Config.mqh\"\n#include \"ctx_stub.h\"\n\n"
        + zero + "\n\n" + stamp + "\n", encoding="utf-8")

    # ---- LogBarDecision, verbatim from the EA ----------------------------
    logfn = grab_block(ea, r"void\s+LogBarDecision\s*\(const\s+datetime", "LogBarDecision")

    # ---- IsNewBar, verbatim ----------------------------------------------
    isnew = grab_block(ea, r"bool\s+IsNewBar\s*\(", "IsNewBar")

    # ---- the new-bar decision block, verbatim ----------------------------
    blk = grab(ea,
               r"      // Audit state is cleared per bar.*?"
               r"LogBarDecision\(now,gatePassed,why\);",
               "new-bar decision block")

    # ---- the SAME block as it stood before Track 1, straight out of git --
    # The A/B inertness claim is about the decision block as a whole, not
    # about whether a file gets written. Comparing the current block against
    # its own pre-Track-1 ancestor is the only version of that test that can
    # actually fail.
    BASELINE = "a373bcd"
    EA_REL = "MQL5/Experts/XAUM15/XAU_M15_Institutional_Adaptive.mq5"
    base_src = subprocess.run(["git", "show", f"{BASELINE}:{EA_REL}"],
                              cwd=ROOT, capture_output=True, text=True, check=True).stdout
    base_blk = grab(base_src,
                    r'      string why="";\n'
                    r'      if\(EntryGatesPass\(now,why\)\) TryEnter\(now\);\n'
                    r'      else                        g_blockReason=why;',
                    f"pre-Track-1 decision block at {BASELINE}")

    (BUILD / "ea_extract.h").write_text(
        "// GENERATED - verbatim from the EA\n#pragma once\n"
        "#include \"Config.mqh\"\n#include \"DecisionLog.mqh\"\n"
        "#include \"setups_extract.h\"\n#include \"ea_stub.h\"\n\n"
        + isnew + "\n\n" + logfn + "\n\n"
        "// The real new-bar block, wrapped so a test can drive it.\n"
        "void RunNewBarBlock(const datetime now)\n  {\n"
        + blk + "\n  }\n\n"
        "// The pre-Track-1 block, verbatim from git " + BASELINE + ".\n"
        "void RunNewBarBlockBaseline(const datetime now)\n  {\n"
        + base_blk + "\n  }\n", encoding="utf-8")

    print(f"extracted: TradeSignal({len(ts.splitlines())} lines), "
          f"{len(enums)} enums, ZeroSignal, StampSignalContext, LogBarDecision, "
          f"new-bar block, pre-Track-1 block")
    print(f"DecisionLog.mqh copied verbatim, sha256[:16]={digest}")


if __name__ == "__main__":
    main()
