#!/usr/bin/env python3
"""
Generate MT5 .set files for the filter ablation matrix (spec 32).

Each run turns exactly ONE filter off relative to the full system, so the
difference in expectancy is attributable to that filter alone. A filter
that does not improve expectancy or profit factor - or that improves net
profit only by increasing drawdown - has not earned its place.

    python tools/make_ablation_sets.py --outdir sets

Load a .set in Strategy Tester -> Inputs -> Load, run the same date range
and modelling for every file, then compare with compare_ablation.py.
"""
import argparse
from pathlib import Path

# Every ablation switch defaults to true = filter active.
ABLATION_FLAGS = [
    ("InpAblSession",       "Session windows"),
    ("InpAblNews",          "News blackout"),
    ("InpAblRegime",        "Market regime gate"),
    ("InpAblLiquidity",     "Liquidity map / Asian range"),
    ("InpAblAMD",           "AMD context"),
    ("InpAblVolumeProfile", "Volume profile location"),
    ("InpAblVWAP",          "VWAP context"),
    ("InpAblDisplacement",  "Displacement confirmation"),
    ("InpAblQuality",       "Quality grading"),
]

# Baseline that every run shares. Only the ablation flag differs.
BASE = {
    "InpEnableTrading":     "true",
    "InpRiskPercent":       "0.75",
    "InpMaxRiskPercent":    "1.0",
    "InpPositionsPerSetup": "3",
    "InpDailyProfitTarget": "3.0",
    "InpDailyLossLimit":    "2.5",
    "InpDD_Preferred":      "35.0",
    "InpDD_Emergency":      "40.0",
    "InpMaxTradesPerDay":   "3",
    "InpEntryMode":         "1",     # ENTRY_RETEST
    "InpAllowBSetup":       "false",
    "InpAllowCSetup":       "false",
    "InpShowDashboard":     "false", # faster tester runs
    "InpWriteTradeLog":     "true",
}


def write_set(path: Path, overrides: dict, note: str) -> None:
    lines = [f"; {note}", "; generated by tools/make_ablation_sets.py", ""]
    merged = dict(BASE)
    merged.update(overrides)
    for key, value in merged.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="sets")
    ap.add_argument("--per-setup", action="store_true",
                    help="also emit one file per setup in isolation (spec 16)")
    args = ap.parse_args()

    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    written = []

    write_set(out / "00_full_system.set", {}, "Full system - all filters active")
    written.append("00_full_system.set")

    for flag, label in ABLATION_FLAGS:
        name = f"ab_{flag.replace('InpAbl', '').lower()}_off.set"
        write_set(out / name, {flag: "false"}, f"Ablation: {label} DISABLED")
        written.append(name)

    # A baseline with every optional filter off isolates the raw entry engine.
    bare = {flag: "false" for flag, _ in ABLATION_FLAGS
            if flag not in ("InpAblSession",)}
    write_set(out / "01_bare_entry_engine.set", bare,
              "Structure + sweep + risk only (session kept for sane hours)")
    written.append("01_bare_entry_engine.set")

    if args.per_setup:
        for letter in ("A", "B", "C"):
            ov = {f"InpEnableSetup{x}": ("true" if x == letter else "false")
                  for x in ("A", "B", "C")}
            name = f"setup_{letter}_only.set"
            write_set(out / name, ov, f"Setup {letter} in isolation (spec 16)")
            written.append(name)

    print(f"wrote {len(written)} set files to {out}/")
    for name in written:
        print(f"  {name}")
    print("\nRun every file over the SAME date range and modelling mode.")
    print("Judge each filter on expectancy and profit factor, not net profit.")


if __name__ == "__main__":
    main()
