#!/usr/bin/env python3
"""
Generate MT5 .set files for the filter ablation matrix (spec 32).

Each run turns exactly ONE filter off relative to the full system, so the
difference in expectancy is attributable to that filter alone. A filter
that does not improve expectancy or profit factor - or that improves net
profit only by increasing drawdown - has not earned its place.

    python tools/make_ablation_sets.py --outdir sets

Load a .set in Strategy Tester -> Inputs -> Load, run the same date range
and modelling for every file, then compare with compare_ablation.py.
"""
import argparse
from pathlib import Path

# Every ablation switch defaults to true = filter active.
ABLATION_FLAGS = [
    ("InpAblSession",       "Session windows"),
    ("InpAblNews",          "News blackout"),
    ("InpAblRegime",        "Market regime gate"),
    ("InpAblLiquidity",     "Liquidity map / Asian range"),
    ("InpAblAMD",           "AMD context"),
    ("InpAblVolumeProfile", "Volume profile location"),
    ("InpAblVWAP",          "VWAP context"),
    ("InpAblDisplacement",  "Displacement confirmation"),
    ("InpAblQuality",       "Quality grading"),
]

# Baseline that every run shares. Only the ablation flag differs.
BASE = {
    "InpEnableTrading":     "true",
    "InpRiskPercent":       "0.5",
    "InpMaxRiskPercent":    "1.0",
    "InpPositionsPerSetup": "1",
    "InpSLMode":            "1",     # SL_FIXED_ATR
    "InpExitMode":          "1",     # EXIT_TIME_STOP_ONLY
    "InpTrendSLATR":        "1.8",
    "InpTimeStopBars":      "120",
    "InpCooldownBarsLoss":  "0",
    "InpEnableSetupA":      "false",
    "InpEnableSetupB":      "false",
    "InpEnableSetupC":      "false",
    "InpEnableSetupD":      "true",
    "InpUseDailyLimits":    "false",  # incompatible with a 23.8% win rate
    "InpDD_Preferred":      "35.0",
    "InpDD_Emergency":      "40.0",
    "InpShowDashboard":     "false",  # faster tester runs
    "InpWriteTradeLog":     "true",
}


def write_set(path: Path, overrides: dict, note: str) -> None:
    lines = [f"; {note}", "; generated by tools/make_ablation_sets.py", ""]
    merged = dict(BASE)
    merged.update(overrides)
    for key, value in merged.items():
        lines.append(f"{key}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="sets")
    ap.add_argument("--per-setup", action="store_true",
                    help="also emit one file per setup in isolation (spec 16)")
    args = ap.parse_args()

    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)
    written = []

    write_set(out / "00_full_system.set", {}, "Full system - all filters active")
    written.append("00_full_system.set")

    for flag, label in ABLATION_FLAGS:
        name = f"ab_{flag.replace('InpAbl', '').lower()}_off.set"
        write_set(out / name, {flag: "false"}, f"Ablation: {label} DISABLED")
        written.append(name)

    # A baseline with every optional filter off isolates the raw entry engine.
    bare = {flag: "false" for flag, _ in ABLATION_FLAGS
            if flag not in ("InpAblSession",)}
    write_set(out / "01_bare_entry_engine.set", bare,
              "Structure + sweep + risk only (session kept for sane hours)")
    written.append("01_bare_entry_engine.set")

    # The outstanding validation test doubles as the affordability answer.
    # On a 1000-unit cent account the minimum lot floors gold near 2% risk
    # per trade but majors near 0.1-0.2% - about 19x finer. So the symbol
    # that could prove the zone is real is also the one small accounts can
    # actually size on.
    write_set(out / "10_crossasset_check.set", {},
              "Trend zone unchanged - run on EURUSD, GBPUSD, XAGUSD. "
              "If the edge does not reproduce off gold, it is gold overfit. "
              "If it does, majors are also affordable at minimum lot.")
    written.append("10_crossasset_check.set")

    # Gold at a 0.5% cap on a small account: the EA will refuse most setups.
    # Run it to see the signal accounting, not to make money.
    write_set(out / "11_gold_strict_cap.set",
              {"InpRiskPercent": "0.5", "InpMaxRiskPercent": "0.5"},
              "Gold with a hard 0.5% cap - expect most signals to be skipped "
              "as unaffordable. Read the SIGNAL ACCOUNTING block.")
    written.append("11_gold_strict_cap.set")

    # Risk ladder: the research measured 0.5/1.0/2.0% at 28/52/84% drawdown.
    for pct, dd in (("0.5", "28%"), ("1.0", "52%"), ("2.0", "84%")):
        name = f"risk_{pct.replace('.', 'p')}pct.set"
        write_set(out / name, {"InpRiskPercent": pct},
                  f"Risk {pct}% per trade - research measured ~{dd} max drawdown")
        written.append(name)

    # Zone boundary perturbation: a real effect sits on a plateau, not a spike.
    for lo, hi in (("0.80", "7.21"), ("1.08", "7.21"),
                   ("1.40", "7.21"), ("1.08", "5.00"), ("1.08", "9.00")):
        name = f"zone_{lo.replace('.', 'p')}_{hi.replace('.', 'p')}.set"
        write_set(out / name, {"InpTrendZoneMin": lo, "InpTrendZoneMax": hi},
                  f"Trend zone [{lo}, {hi}] - boundary sensitivity")
        written.append(name)

    if args.per_setup:
        for letter in ("A", "B", "C", "D"):
            ov = {f"InpEnableSetup{x}": ("true" if x == letter else "false")
                  for x in ("A", "B", "C", "D")}
            name = f"setup_{letter}_only.set"
            write_set(out / name, ov, f"Setup {letter} in isolation")
            written.append(name)

    print(f"wrote {len(written)} set files to {out}/")
    for name in written:
        print(f"  {name}")
    print("\nRun every file over the SAME date range and modelling mode.")
    print("Judge each filter on expectancy and profit factor, not net profit.")


if __name__ == "__main__":
    main()
